// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3504.SampleMecanumBot;

import org.usfirst.frc3504.SampleMecanumBot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import org.usfirst.frc3504.SampleMecanumBot.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    public Joystick mecanumJoystick;


    public OI() {

        mecanumJoystick = new Joystick(0);

        SmartDashboard.putData("DriveByMecanum", new DriveByMecanum());

    }

    public Joystick getMecanumDrive() {
        return mecanumJoystick;
    }

}

