// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3504.SampleMecanumBot.subsystems;

import org.usfirst.frc3504.SampleMecanumBot.RobotMap;
import org.usfirst.frc3504.SampleMecanumBot.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.drive.MecanumDrive;


/**
 *
 */
public class MecanumChassis extends Subsystem {
	//x or o shape? most likely is the x shape.

    private final WPI_TalonSRX rightFront = RobotMap.mecanumChassisTalonSRX3;
    private final WPI_TalonSRX rightBack = RobotMap.mecanumChassisTalonSRX4;
    private final WPI_TalonSRX leftFront = RobotMap.mecanumChassisTalonSRX2;
    private final WPI_TalonSRX leftBack = RobotMap.mecanumChassisTalonSRX1;

    private MecanumDrive m_drive;
    
    public MecanumChassis() {
    	//invert or reverse the motors here
    	m_drive = new MecanumDrive(leftFront,leftBack,rightFront,rightBack);
    }
    

    @Override
    public void initDefaultCommand() {
    	setDefaultCommand(new DriveByMecanum());
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    public void driveByMecanum(double ySpeed, double xSpeed, double zRotation) {
    	m_drive.driveCartesian(ySpeed, xSpeed, zRotation);
    }
    
    
    public void stop() {
    	m_drive.stopMotor();
    }

}

