// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3504.SampleChassisBot;

import org.usfirst.frc3504.SampleChassisBot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
//import org.usfirst.frc3504.SampleChassisBot.subsystems.*;
import edu.wpi.first.wpilibj.buttons.Button;
//import edu.wpi.first.wpilibj.buttons.JoystickButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    public Joystick tankDrive;
    public Joystick arcadeDrive;
    
    Button button1; //Open Pneumatic 
	Button button2; //Close Pneumatic


    public OI() {

        arcadeDrive = new Joystick(1);
        //make sure that tank uses the logitech dual controller (basically the dual controller)
        tankDrive = new Joystick(0);
        
        //button1 = new JoystickButton(tankDrive, 1); //Open Pneumatic 
    	//button2 = new JoystickButton(tankDrive, 2); //Close Pneumatic

        //button1.whenPressed(new OpenPneumatic());
		
        // SmartDashboard Buttons
        SmartDashboard.putData("DriveByTank", new DriveByTank());
        SmartDashboard.putData("DriveByArcade", new DriveByArcade());
    }

    public Joystick getTankDrive() {
        return tankDrive;
    }

    public Joystick getArcadeDrive() {
        return arcadeDrive;
    }

}

