// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3504.SampleChassisBot;

//import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // when labeling motors, 0 is never used, makes it easier
    /*
     * talons are positioned like this ||-----|| |1---4| ||2---5|| |3---6| ||-----||
     * sides may vary like is 1 is actually left (could be right side)
     */

    // Talon SRX ID numbers assigned via the Phoenix Tuning utility
    public static final int DRIVE_LEFT_MASTER_TALON = 2;
    public static final int DRIVE_LEFT_FOLLOWER_TALON_A = 3;
    //public static final int DRIVE_LEFT_FOLLOWER_TALON_B = 3;

    public static final int DRIVE_RIGHT_MASTER_TALON = 5;
    public static final int DRIVE_RIGHT_FOLLOWER_TALON_A = 6;
    //public static final int DRIVE_RIGHT_FOLLOWER_TALON_B = 6;
}
