// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3504.SampleChassisBot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3504.SampleChassisBot.Robot;


public class DriveByArcade extends Command {

	public DriveByArcade() {
		requires(Robot.chassis);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	//uses the one stick, non-twist controller.
    	//get the y to be the mag and the x to be the rotation, the plane is the standard
    	//graph plane, if the plane was put flat on the controller (y is forward back, x
    	//left right)
    	//for some reason on the bot, y negative is forward... (basically check front back)
    	double y = Robot.oi.getArcadeDrive().getY(); 
    	double x = Robot.oi.getArcadeDrive().getX() * (-1);
    	if (y > 0) x = x * (-1); //This is for turning when going backwards
    	
    	System.out.println("y: " + y);
    	System.out.println("x: " + x);
    	
    	Robot.chassis.driveByArcade(y, x);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.chassis.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
