// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3504.SampleChassisBot.subsystems;

import org.usfirst.frc3504.SampleChassisBot.Robot;
import org.usfirst.frc3504.SampleChassisBot.RobotMap;
import org.usfirst.frc3504.SampleChassisBot.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

import com.ctre.phoenix.motorcontrol.FollowerType;
import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;


public class Chassis extends Subsystem {
	//probably should come up with better names
    private final WPI_TalonSRX talonSRX1 = RobotMap.chassisTalonSRX1;
    private final WPI_TalonSRX talonSRX2 = RobotMap.chassisTalonSRX2;
    private final WPI_TalonSRX talonSRX3 = RobotMap.chassisTalonSRX3;
    private final WPI_TalonSRX talonSRX4 = RobotMap.chassisTalonSRX4;
    private final WPI_TalonSRX talonSRX5 = RobotMap.chassisTalonSRX5;
    private final WPI_TalonSRX talonSRX6 = RobotMap.chassisTalonSRX6;
    
    private DifferentialDrive drive;


    public Chassis() {
    	//This is the constructor
    	
    	//Safety and brakes ----------------------------------
    	talonSRX1.setNeutralMode(NeutralMode.Brake);
    	talonSRX2.setNeutralMode(NeutralMode.Brake);
    	talonSRX3.setNeutralMode(NeutralMode.Brake);
    	
    	talonSRX4.setNeutralMode(NeutralMode.Brake);
    	talonSRX5.setNeutralMode(NeutralMode.Brake);
    	talonSRX6.setNeutralMode(NeutralMode.Brake);
    	
    	talonSRX1.setSafetyEnabled(false);
    	talonSRX2.setSafetyEnabled(false);
    	talonSRX3.setSafetyEnabled(false);
    	
    	talonSRX4.setSafetyEnabled(false);
    	talonSRX5.setSafetyEnabled(false);
    	talonSRX6.setSafetyEnabled(false);
    	//-----------------------------------------------------
    	
    	//reverse();
    	
    	setFollowerMode();
    	
    	//invert(true); //uncomment if needed
    	//if needed to invert the talons, do before putting into the drive
    	drive = new DifferentialDrive(talonSRX4, talonSRX1);
    	
    	drive.setSafetyEnabled(false);
    	//this line is to set it so the joystick isn't too sensitive to input
    	drive.setDeadband(0.02);
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new DriveByTank());

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
    	//if you had something that needed to executed on a periodic sort of time
    	//instead of tiem, this is where you would put the commands
    }
    
    public void driveByTank(double left, double right) {   
    	drive.tankDrive(left, right);
    }
    
    public void driveByArcade(double mag, double rotate) {
    	// speed and how tight the rotation is [-1,1]
    	drive.arcadeDrive(mag, rotate);
    }
    
    public void invert(boolean x) {
    	//if the moters are spinning in opposite directions
    	talonSRX1.setInverted(false);
    	talonSRX2.setInverted(false);
    	talonSRX3.setInverted(false);
    	
    	talonSRX4.setInverted(x);
    	talonSRX5.setInverted(x);
    	talonSRX6.setInverted(x);
    }
    
    public void reverse() {
    	//if the motors are together but completely reversed (do not pair with invert)
    	talonSRX1.setInverted(true);
    	talonSRX3.setInverted(true);
    	talonSRX5.setInverted(true);
    	
    	talonSRX2.setInverted(true);
    	talonSRX4.setInverted(true);
    	talonSRX6.setInverted(true);
    }
    
    public void setFollowerMode() {
    	//follower code
    	talonSRX2.follow(talonSRX1, FollowerType.PercentOutput);
    	talonSRX3.follow(talonSRX1, FollowerType.PercentOutput);
    	
    	talonSRX5.follow(talonSRX4, FollowerType.PercentOutput);
    	talonSRX6.follow(talonSRX4, FollowerType.PercentOutput);
    }
    
    public void stop() {
    	drive.stopMotor();
    }


}

